Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data collection and Pre-Processing

In [3]:
#loading the data from csv file to a pandas dataframe
movies_data=pd.read_csv('/content/movies.csv')

In [4]:
#printing the first 5 rows of dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [5]:
movies_data.shape

(4803, 24)

In [6]:
#selecting the relevant features for recommendation
selected_features=['genres', 'keywords', 'overview', 'tagline', 'title', 'cast', 'director']
print(selected_features)

['genres', 'keywords', 'overview', 'tagline', 'title', 'cast', 'director']


In [7]:
#replacing the null values with null string
for features in selected_features:
 movies_data[features]=movies_data[features].fillna('')

In [8]:
#combining all the 5 selected features
combined_features=movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['overview']+' '+movies_data['tagline']+' '+movies_data['title']+' '+movies_data['cast']+' '+movies_data['director']

In [9]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [10]:
#converting the text data to feature vectors
vectorizer=TfidfVectorizer()

In [11]:
feature_vector=vectorizer.fit_transform(combined_features)

In [12]:
print(feature_vector)

  (0, 4405)	0.13007397510161756
  (0, 14533)	0.08286987957510253
  (0, 23687)	0.1475450502196134
  (0, 18206)	0.12094554394544946
  (0, 15951)	0.16869852873908397
  (0, 26493)	0.11410401853770415
  (0, 30347)	0.14830419354529692
  (0, 25397)	0.1564513257868596
  (0, 24138)	0.16540428104909333
  (0, 31299)	0.14830419354529692
  (0, 30893)	0.17959863615914348
  (0, 24180)	0.10875369262389524
  (0, 2127)	0.1996044560566861
  (0, 19876)	0.030846726810594093
  (0, 30868)	0.0710516516949864
  (0, 9290)	0.14044787266458833
  (0, 5389)	0.16249854865534707
  (0, 1037)	0.12044205276704567
  (0, 1275)	0.0517167846401998
  (0, 22040)	0.16390865881038189
  (0, 1315)	0.031279256768719746
  (0, 20121)	0.15869561879031263
  (0, 10623)	0.13632661307394978
  (0, 3061)	0.09808742782138465
  (0, 28189)	0.14279919495279256
  :	:
  (4802, 19703)	0.058390572523091544
  (4802, 12241)	0.07492190909958076
  (4802, 30413)	0.07402585257774721
  (4802, 9576)	0.0674085486675589
  (4802, 19949)	0.05488577822704526
 

cosine similarity

In [13]:
#getting the similarity scores using cosine similarity
similarity=cosine_similarity(feature_vector)

In [14]:
print(similarity)

[[1.         0.05399851 0.03084844 ... 0.02434614 0.02809646 0.00665587]
 [0.05399851 1.         0.04098103 ... 0.05353934 0.03667414 0.01552356]
 [0.03084844 0.04098103 1.         ... 0.02269726 0.0425641  0.01228775]
 ...
 [0.02434614 0.05353934 0.02269726 ... 1.         0.02986951 0.03920937]
 [0.02809646 0.03667414 0.0425641  ... 0.02986951 1.         0.02879619]
 [0.00665587 0.01552356 0.01228775 ... 0.03920937 0.02879619 1.        ]]


In [15]:
print(similarity.shape)

(4803, 4803)


In [16]:
movie_name=input('Enter your favourite movie name: ')

Enter your favourite movie name: iron man


In [17]:
#creating a movie list with all the dataset given
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [18]:
#finding close match to the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [19]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [20]:
#finding the index of the movie
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)


68


In [21]:
#getting the list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.04858353025503669), (1, 0.034402344733989586), (2, 0.010301525424956253), (3, 0.006223824988768591), (4, 0.024872978243300422), (5, 0.025900816975771693), (6, 0.03206993145086021), (7, 0.17626921426749495), (8, 0.009146132836817412), (9, 0.0341034540061075), (10, 0.040421561744814316), (11, 0.012769921962739107), (12, 0.015787238625059298), (13, 0.00994861548304168), (14, 0.0713147541656277), (15, 0.02630758710632095), (16, 0.12800053826988375), (17, 0.015569731972069343), (18, 0.02088898689243991), (19, 0.041104177056169894), (20, 0.04164262876004683), (21, 0.02715593696595206), (22, 0.008760721380106168), (23, 0.015824967957481197), (24, 0.016910248680110634), (25, 0.0033047546168936065), (26, 0.13439160903673494), (27, 0.03220163772266192), (28, 0.03440269430029269), (29, 0.0092834286141939), (30, 0.08406768703156885), (31, 0.3150107510046931), (32, 0.024810102023011732), (33, 0.07317775305538607), (34, 0.005256992130410431), (35, 0.019833427234006162), (36, 0.023588684859880

In [22]:
len(similarity_score)


4803

In [23]:
#sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(68, 1.0), (79, 0.3678810386218641), (31, 0.3150107510046931), (7, 0.17626921426749495), (26, 0.13439160903673494), (16, 0.12800053826988375), (511, 0.11415468944095045), (182, 0.11049794716683105), (64, 0.10488211427755577), (3623, 0.10189929703406754), (94, 0.09616281195134325), (4033, 0.08452663267414781), (30, 0.08406768703156885), (618, 0.0825462024961927), (46, 0.08168728882824969), (174, 0.08056589176050646), (783, 0.08039355490404283), (3133, 0.07693847803449275), (101, 0.07693846919217372), (85, 0.07666062407625433), (203, 0.07513744872750992), (2875, 0.07505704712461227), (198, 0.07445348298075158), (3466, 0.07435760786686184), (1740, 0.074310326915836), (131, 0.07344401616767435), (33, 0.07317775305538607), (318, 0.07167576554701938), (1177, 0.07164731672311707), (725, 0.07154972417267536), (2229, 0.07151802601107231), (14, 0.0713147541656277), (1406, 0.07073133900948127), (788, 0.07056548865025603), (1135, 0.07024365484514397), (169, 0.07023508329023337), (1282, 0.06987985

In [24]:
#print the name of similar movies based on the index
print('Movies suggested for you: \n')
i=1
for movies in sorted_similar_movies:
  index=movies[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_from_index)
    i+=1

Movies suggested for you: 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . Captain America: Civil War
6 . The Avengers
7 . X-Men
8 . Ant-Man
9 . X-Men: Apocalypse
10 . Made
11 . Guardians of the Galaxy
12 . Super
13 . Spider-Man 2
14 . Mystery Men
15 . X-Men: Days of Future Past
16 . The Incredible Hulk
17 . Mortdecai
18 . The Devil's Tomb
19 . X-Men: First Class
20 . Captain America: The Winter Soldier
21 . X2
22 . Two Lovers
23 . R.I.P.D.
24 . Sliding Doors
25 . Kick-Ass 2
26 . G-Force
27 . X-Men: The Last Stand
28 . Surf's Up
29 . Sin City


Movie Recommendation system

In [26]:
movie_name=input('Enter your favourite movie name: ')
list_of_all_titles = movies_data['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print('Movies suggested for you: \n')
i=1
for movies in sorted_similar_movies:
  index=movies[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_from_index)
    i+=1

Enter your favourite movie name: avatar
Movies suggested for you: 

1 . Avatar
2 . Alien
3 . Lifeforce
4 . Moonraker
5 . Aliens
6 . Lost in Space
7 . Star Trek Beyond
8 . Gattaca
9 . Guardians of the Galaxy
10 . Zathura: A Space Adventure
11 . Gravity
12 . Space Chimps
13 . Lockout
14 . The Book of Life
15 . Apollo 18
16 . Treasure Planet
17 . Cargo
18 . Sunshine
19 . Star Trek Into Darkness
20 . Space Dogs
21 . Men in Black
22 . Men in Black II
23 . Transformers: Dark of the Moon
24 . Tears of the Sun
25 . Starship Troopers
26 . The Right Stuff
27 . Lara Croft Tomb Raider: The Cradle of Life
28 . Deep Impact
29 . Sphere
